<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>ClevoFan.Tray</RootNamespace>
    <AssemblyName>ClevoFan.Tray</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>..\..\MyFanControl\res\MyFanControl.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClevoFan.Core\ClevoFan.Core.csproj" />
  </ItemGroup>

</Project>
